### PR TITLE
docs: Add Autogen integration section

### PR DESCRIPTION
**Pull request by Anush008**
Adds Autogen to the list of supported integrations with usage info.

### CODE REVIEW

**Comment by Anush008** [comment]
Waiting on https://github.com/microsoft/autogen/pull/303 to be merged.

**Comment by Anush008** [comment]
New section preview link: https://deploy-preview-365--condescending-goldwasser-91acf0.netlify.app/documentation/integrations/autogen/

**Comment by Anush008** [comment]
@kacperlukawski, review please.

**Review by kacperlukawski — APPROVED** [review]
It looks good to me!

**Pull request merged**
