### PR TITLE
About us page

### PR DESCRIPTION
**Pull request by nshershnev**

### CODE REVIEW

**Review by trean — CHANGES_REQUESTED** [review]
Thank you for PR!
There seems to be an issue with this section:

Screenshot 2024-04-11 at 14 49 57

**Comment by nshershnev** [comment]
> Thank you for PR! There seems to be an issue with this section:
> 
> Screenshot 2024-04-11 at 14 49 57

@trean actually it follows the design in Figma (scrollable component from left to right for the whole screen). Do we need to have a special mode for carousel component for extra large screens in this case?

**Comment by nshershnev** [comment]
@trean add the required changes to resize carousel component on the x-large screens

**Review by trean — APPROVED** [review]
Thank you!

**Pull request merged**
