### PR TITLE
docs: Pulumi integration

### PR DESCRIPTION
**Pull request by Anush008**
## [PREVIEW](https://deploy-preview-1177--condescending-goldwasser-91acf0.netlify.app/documentation/platforms/pulumi/)

### CODE REVIEW

**Review by mikheillomidzeq — APPROVED** [review]
Nice work, Thank you. 

I have an optional suggeesstion, it may be helpful, if we add small explanation about packages in `Usage` section. 

During cluster creation, there is used `package_id`, which does not make any sense for user.

**Review by mikheillomidzeq — APPROVED** [review]
Really nice. Thank you!

**Comment by Anush008** [comment]
> During cluster creation, there is used package_id, which does not make any sense for user.

Got it. Will do.

**Comment by Anush008** [comment]
@mikheillomidzeq, I've moved the mention of bookings/package IDs to the top.

See https://deploy-preview-1177--condescending-goldwasser-91acf0.netlify.app/documentation/platforms/pulumi/#usage

**Pull request merged**
