### PR TITLE
Cheshire cat

### PR DESCRIPTION
**Pull request by nickprock**
Added a new article about how Cheshire Cat uses Qdrant

### CODE REVIEW

**Comment by nickprock** [comment]
Hi @Anush008 , I added a new link.

**Comment by Anush008** [comment]
@nickprock, this was based on an earlier version I think.

**Comment by Anush008** [comment]
`qdrant-landing/content/documentation/integrations/cheshire-cat.md`

are now in `/frameworks`. PR adds them back to `/integrations`.

**Comment by nickprock** [comment]
No problem, I close the PR.

**Comment by Anush008** [comment]
You can do a new one on the latest with the added link.

**Pull request closed without merging**
