### PR TITLE
google fonts upd: Roboto and Roboto Mono

### PR DESCRIPTION
**Pull request by trean**
- fixes _and changes_ code blocks font, now they use Roboto Mono,
- updated fonts, coming from Google Fonts

### CODE REVIEW

**Comment by generall** [comment]
Let's undo everything and only change article font to the same as used in documentation.

Use same font size in docs and articles  - 16px

Also change font in article list, so it is not serif.

**Comment by timvisee** [comment]
The monospace font is a bit too thin to my liking:

image

Maybe we can switch to 400. What do you think?

**Comment by trean** [comment]
@timvisee As you can see in the above comment, we decided not to move to the Roboto at all and to change only the articles font and docs and articles font size. This is done in #322. This PR will be closed.

**Comment by trean** [comment]
@generall requested changes are in #322.

**Pull request closed without merging**
