### PR TITLE
feat: CMD + K to search

### LINKED ISSUE #875: feat: Please enable CMD+K shortcut to search the qdrant docs
Please enable CMD+K shortcut to search the qdrant docs.  It'll help with finding information quickly.

### PR DESCRIPTION
**Pull request by Anush008**
Fixes #875

### CODE REVIEW

**Comment by generall** [comment]
Thanks for taking care of it! Unfortunately it is going to be overwritten by the new design changes, if we merge it into `theme/qdrant`. @Anush008 could you please make this changes in `new-design` branch and move into `theme/qdrant-2024`

**Comment by Anush008** [comment]
We merge this for the current site?

**Comment by trean** [comment]
@generall shouldn't it be a part of the plugin?

**Comment by Anush008** [comment]
Live!

**Pull request closed without merging**
