### PR TITLE
remove all instances of plural from with_vector

### PR DESCRIPTION
**Pull request by davidmyriel**
Please LMK if I missed anything?

### CODE REVIEW

**Comment by agourlay** [comment]
@joein We have users being confused regularly by this on Discord.
This looks correct to me but I have just realized you performed the opposite transformation https://github.com/qdrant/landing_page/pull/202

What is the correct usages here?

**Comment by davidmyriel** [comment]
There could be a mixup as per Luis' PR here: https://github.com/qdrant/qdrant/pull/1697

**Comment by joein** [comment]
@agourlay we used to have a lot of complaints about it, but i haven't seen them for a while (since we introduced checks for incorrect keyword arguments in python client)
(correct me if i am wrong)

python client uses `with_vectors`

**Comment by joein** [comment]
@davidmyriel sorry, i didn't see your comment in #202, `with_vector` does not work in python, it raises an exception

**Comment by joein** [comment]
Actually, I think we can support both in python client, it is not that hard to implement

**Comment by davidmyriel** [comment]
Closing as with_vectors seems appropriate

**Pull request closed without merging**
