### PR TITLE
Add Stars page

### PR DESCRIPTION
**Pull request by nastyapash**

### CODE REVIEW

**Comment by nastyapash** [comment]
@trean In Figma in the mobile and desktop versions the people in block “Meet our Stars" are different. I used people from the desktop version

**Review by trean — APPROVED** [review]
Looks good, thank you! We will merge it a little bit later.

**Comment by sabrinaaquino** [comment]
Let's wait till the final list of the Stars. For reference, refer to the announcement blog.

**Comment by trean** [comment]
@sabrinaaquino Do we have the final list of the Stars already? It would be good to prepare this page to be published.

**Comment by sabrinaaquino** [comment]
@trean it's the people from the Stars page plus [Haydar Kulekci](https://www.linkedin.com/in/hkulekci/) and [Nicola Procopio](https://www.linkedin.com/in/nicolaprocopio/). You can use their linkedin profile picture for it.

**Pull request merged**
